[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 8888

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[site]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  domain = "fruitygulpjuice.com"
